# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

target 'suracare' do
  # Comment this line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for suracare
  pod 'Firebase'
  pod 'ReactiveCocoa'
  target 'suracareTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'suracareUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
